name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install --upgrade pip
      - run: pip install pytest -r requirements.txt
      - run: pip install --editable . || true
      - run: python run_tests.py
      - run: pytest || true
